apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:konnectivity-agent
  labels:
    kubernetes.io/cluster-service: "true"
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list"]
