apiVersion: v1
kind: Service
metadata:
  name: konnectivity-agent
  namespace: kube-system
spec:
  selector:
    k8s-app: konnectivity-agent
  clusterIP: None
  ports:
  - protocol: TCP
    port: 8093
    targetPort: 8093
