apiVersion: v1
kind: Service
metadata:
  name: konnectivity-server
  namespace: kube-system
spec:
  selector:
    k8s-app: konnectivity-server
  ports:
  - protocol: TCP
    port: 8091
    targetPort: 8091
    name: agent
